# Generated by Django 2.1.7 on 2019-03-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190317_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employees',
        ),
    ]
