# Generated by Django 2.1.7 on 2019-03-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_delete_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_id', models.CharField(max_length=20, unique=True)),
                ('First_name', models.CharField(max_length=10)),
                ('Last_name', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                
            ],
        ),
    ]
